[package]
name = "library-scanner"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
anyhow.workspace = true
chrono.workspace = true
core-db = { path = "../core-db" }
hex.workspace = true
lofty.workspace = true
protocol = { path = "../protocol" }
serde.workspace = true
sha2.workspace = true
sqlx.workspace = true
tokio.workspace = true
tracing.workspace = true
walkdir.workspace = true
