[package]
name = "core-daemon"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[[bin]]
name = "local-music-core-daemon"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
core-api = { path = "../core-api" }
core-config = { path = "../core-config" }
core-db = { path = "../core-db" }
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[target.'cfg(windows)'.dependencies]
windows-service = "0.8"
