[package]
name = "playback"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
anyhow.workspace = true
chrono.workspace = true
cpal.workspace = true
protocol = { path = "../protocol" }
rodio.workspace = true
serde.workspace = true
tokio.workspace = true
uuid.workspace = true
